apiVersion: v1
kind: Service
metadata:
  name: service-sts-example
spec:
  selector:
    app: stateful
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  externalIPs:
  - 172.17.0.71    
