version: '2.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.30
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    restart: always
    ports:
      - 9093:9093
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.30
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181      
      
  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    restart: always
    ports:
      - 9094:9094
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.30
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      
  kafka-manager:
    image: deltaprojects/kafka-manager
    container_name: kafka-manager
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: password
    