# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: training
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
      
volumes:
  postgres-data:    